# **Material Properties Database from `01_touloukian_nonmetals_cr_oxide.md`**

*   **SPECIFICATION TABLE NO. 77: NORMAL TOTAL EMITTANCE OF CHROMIUM OXIDES**
    *   **DATA TABLE NO. 77: NORMAL TOTAL EMITTANCE OF CHROMIUM OXIDE**
        *   [Temperature, T, K; Emittance, E]
        *   CURVE 1
        *   CURVE 2
        *   CURVE 3
        *   CURVE 4

*   **SPECIFICATION TABLE NO. 78: NORMAL SPECTRAL EMITTANCE OF CHROMIUM OXIDES**
    *   **DATA TABLE NO. 78: NORMAL SPECTRAL EMITTANCE OF CHROMIUM OXIDES**
        *   [Wavelength, λ, µm; Emittance, E; Temperature, T, K]
        *   CURVE 1 (T=1273)
        *   CURVE 2 (T=1023)
        *   CURVE 3 (T=1273)
        *   CURVE 4 (T=1273)
        *   CURVE 5 (T=1273)
        *   CURVE 6 (T=878)
        *   CURVE 7 (T=1073)
        *   CURVE 8 (T=1273)
        *   CURVE 9 (T=1273)

*   **SPECIFICATION TABLE NO. 79: NORMAL SPECTRAL REFLECTANCE OF CHROMIUM OXIDES**
    *   **DATA TABLE NO. 79: NORMAL SPECTRAL REFLECTANCE OF CHROMIUM OXIDES**
        *   [Wavelength, λ, µm; Reflectance, p; Temperature, T, K]
        *   CURVE 1 (T=298)
        *   CURVE 2 (T~298)
        *   CURVE 3 (T~298)
        *   CURVE 4 (T~298)
        *   CURVE 5 (T~298)
        *   CURVE 6 (T~298)
        *   CURVE 7 (T~298)


----

### SPECIFICATION TABLE NO. 77: NORMAL TOTAL EMITTANCE OF CHROMIUM OXIDES

| Curve No. | Ref. No. | Year | Temperature Range, K | Geometry θ' | Reported Error, % | Composition (weight percent), Specifications and Remarks |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1* | 28 | 1963 | 1023 | ~0° | | Cr₂O₃; sintered at 2173 K for 2 hrs (setter material Cr₂O₃); density 3.15 g cm⁻³, theoretical density 5.21 g cm⁻³; integrated from spectral data (1-15 µm); [Authors' designation: Sample No. 115]. |
| 2* | 200 | 1962 | 1273 | ~0° | | Cr₂O₃; 99.5 pure; 1.3 mm thick plate; sintered at 2123 K for 2 hrs. |
| 3* | 362 | 1964 | 873-1273 | 0° | | Cr₂O₃; 99.5 pure powder, McGean Chemical Co.; sintered 2 hrs at 2173 K. |
| 4* | 362 | 1964 | 873-1273 | 0° | | Cr₂O₃; similar to above specimen and conditions except calculated from spectral data (1-15 µm). |

---

### DATA TABLE NO. 77: NORMAL TOTAL EMITTANCE OF CHROMIUM OXIDE
[Temperature, T, K; Emittance, E]

**CURVE 1**

| T | E |
| :--- | :--- |
| 1023 | 0.91 |

**CURVE 2**

| T | E |
| :--- | :--- |
| 1273 | 0.69 |

**CURVE 3**

| T | E |
| :--- | :--- |
| 873 | 0.85 |
| 1073 | 0.90 |
| 1273 | 0.80 |

**CURVE 4**

| T | E |
| :--- | :--- |
| 873 | 0.86 |
| 1073 | 0.91 |
| 1273 | 0.82 |

*No plot given*

---

### SPECIFICATION TABLE NO. 78: NORMAL SPECTRAL EMITTANCE OF CHROMIUM OXIDES

| Curve No. | Ref. No. | Year | Temperature K | Wavelength Range, µm | Geometry θ' | Reported Error, % | Composition (weight percent), Specifications, and Remarks |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | 200 | 1962 | 1273 | 1.00-15.0 | ~0° | | Cr₂O₃; 99.5 pure; 1.3 mm thick plate; sintered at 2123 K for 2 hrs; data extracted from smooth curve. |
| 2 | 28 | 1963 | 1023 | 1.00-15.0 | ~0° | | Cr₂O₃; sintered at 2173 K for 2 hrs (setter material Cr₂O₃); density 3.15 g cm⁻³, theoretical density 5.21 g cm⁻³; data extracted from smooth curve; [Authors' designation; Sample No. 115]. |
| 3 | 382 | 1965 | 1273 | 1.00-15.0 | 0° | | Cr₂O₃; sintered 15 hrs at 1273 K; density 2.05; data extracted from smooth curve. |
| 4 | 382 | 1965 | 1273 | 1.00-15.0 | 0° | | Above specimen and conditions except sintered additionally 2 hrs at 1373 K, 2 hrs at 1473 K, and 2 hrs at 1573 K; density increased to 2.87. |
| 5 | 382 | 1965 | 1273 | 1.00-15.0 | 0° | | Above specimen and conditions except sintered an additional 2 hrs at 1923 K; density decreased to 2.23. |
| 6 | 362 | 1964 | 878 | 1.00-15.0 | ~0° | | Cr₂O₃; 99.5 pure powder, McGean Chemical Co.; sintered 2 hrs at 2173 K; data extracted from smooth curve. |
| 7* | 362 | 1964 | 1073 | 1.00-15.0 | ~0° | | Above specimen and conditions. |
| 8 | 362 | 1964 | 1273 | 1.00-15.00 | ~0° | | Above specimen and conditions. |
| 9 | 393 | 1966 | 1273 | 1.00-15.00 | ~0° | | Cr₂O₃; cold pressed and sintered at 2123 K for 2 hrs; 2 or 3 wt. percent polyvinyl binder; density 3.29 g cm⁻³; data extracted from smooth curve. |

*Not shown on plot*

---

### DATA TABLE NO. 78: NORMAL SPECTRAL EMITTANCE OF CHROMIUM OXIDES
[Wavelength, λ, µm; Emittance, E; Temperature, T, K]

**CURVE 1 (T=1273)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.760 |
| 1.30 | 0.660 |
| 1.40 | 0.640 |
| 1.60 | 0.640 |
| 1.90 | 0.675 |
| 3.00 | 0.675 |
| 3.60 | 0.685 |
| 4.00 | 0.690 |
| 4.20 | 0.670 |
| 4.30 | 0.665 |
| 4.40 | 0.675 |
| 6.00 | 0.685 |
| 6.80 | 0.710 |
| 7.60 | 0.750 |
| 8.00 | 0.775 |
| 8.60 | 0.800 |
| 9.00 | 0.825 |
| 10.0 | 0.845 |
| 10.2 | 0.860 |
| 10.4 | 0.860 |
| 10.4 | 0.880 |
| 11.8 | 0.890 |
| 13.2 | 0.910 |
| 14.0 | 0.920 |
| 14.1 | 0.920 |
| 14.7 | 0.815 |
| 14.9 | 0.780 |
| 15.0 | 0.780 |

**CURVE 2 (T=1023)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.885 |
| 1.16 | 0.835 |
| 1.50 | 0.816 |
| 1.78 | 0.846 |
| 1.92 | 0.881 |
| 2.10 | 0.905 |
| 2.38 | 0.922 |
| 2.54 | 0.922 |
| 2.62 | 0.900 |
| 2.96 | 0.913 |
| 3.16 | 0.947 |
| 3.79 | 0.952 |
| 4.16 | 0.965 |
| 4.27 | 0.930 |
| 4.50 | 0.927 |
| 4.62 | 0.937 |
| 5.62 | 0.924 |
| 5.72 | 0.935 |
| 5.88 | 0.921 |
| 6.52 | 0.927 |
| 6.65 | 0.938 |
| 6.72 | 0.922 |
| 6.99 | 0.931 |
| 7.98 | 0.931 |
| 8.13 | 0.899 |
| 8.29 | 0.899 |
| 8.43 | 0.911 |
| 8.74 | 0.911 |
| 8.80 | 0.922 |
| 8.88 | 0.896 |
| 8.98 | 0.915 |
| 9.26 | 0.915 |
| 9.50 | 0.906 |
| 9.78 | 0.916 |
| 10.0 | 0.923 |
| 10.5 | 0.938 |
| 11.5 | 0.948 |
| 12.7 | 0.955 |
| 12.8 | 0.965 |
| 13.0 | 0.956 |
| 13.4 | 0.968 |
| 13.8 | 0.973 |
| 14.0 | 0.962 |
| 14.2 | 0.950 |
| 14.4 | 0.945 |
| 14.7 | 0.907 |
| 14.9 | 0.896 |
| 15.0 | 0.915 |

**CURVE 3 (T=1273)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.671 |
| 5.05 | 0.706 |
| 5.99 | 0.706 |
| 7.00 | 0.761 |
| 9.37 | 0.880 |
| 10.3 | 0.908 |
| 12.7 | 0.957 |
| 13.7 | 0.954 |
| 14.2 | 0.933 |
| 14.6 | 0.879 |
| 15.0 | 0.828 |

**CURVE 4 (T=1273)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.726 |
| 5.46 | 0.749 |
| 6.77 | 0.765 |
| 7.83 | 0.805 |
| 9.31 | 0.879 |
| 10.3 | 0.908 |
| 12.7 | 0.957 |
| 13.7 | 0.954 |
| 14.2 | 0.933 |
| 14.6 | 0.879 |
| 15.0 | 0.828 |

**CURVE 5 (T=1273)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.763 |
| 4.81 | 0.767 |
| 5.90 | 0.770 |
| 6.87 | 0.799 |
| 7.55 | 0.848 |
| 9.18 | 0.912 |
| 10.1 | 0.944 |
| 11.0 | 0.966 |
| 12.8 | 0.991 |
| 13.3 | 0.994 |
| 14.0 | 0.979 |
| 14.5 | 0.948 |
| 15.0 | 0.897 |

**CURVE 6 (T=878)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.779 |
| 1.40 | 0.798 |
| 2.01 | 0.810 |
| 2.76 | 0.823 |
| 3.11 | 0.841 |
| 6.46 | 0.890 |
| 8.11 | 0.900 |
| 10.4 | 0.923 |
| 12.1 | 0.925 |
| 13.2 | 0.940 |
| 13.6 | 0.937 |
| 13.8 | 0.926 |
| 14.1 | 0.892 |
| 14.6 | 0.805 |
| 14.7 | 0.784 |
| 15.0 | 0.769 |

**CURVE 7 (T=1073)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.863 |
| 2.00 | 0.867 |
| 2.63 | 0.889 |
| 5.12 | 0.907 |
| 6.44 | 0.913 |
| 7.41 | 0.926 |
| 8.54 | 0.926 |
| 12.7 | 0.973 |
| 14.0 | 0.980 |
| 14.2 | 0.953 |
| 14.5 | 0.901 |
| 14.7 | 0.875 |
| 15.0 | 0.856 |

**CURVE 8 (T=1273)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.735 |
| 1.97 | 0.778 |
| 3.11 | 0.841 |
| 6.43 | 0.882 |
| 8.11 | 0.900 |
| 10.4 | 0.924 |
| 11.9 | 0.940 |
| 12.2 | 0.947 |
| 13.3 | 0.954 |
| 13.7 | 0.962 |
| 13.9 | 0.963 |
| 14.4 | 0.926 |
| 14.9 | 0.873 |
| 15.0 | 0.856 |

**CURVE 9 (T=1273)**

| λ | E |
| :--- | :--- |
| 1.00 | 0.670 |
| 2.28 | 0.672 |
| 3.16 | 0.674 |
| 4.61 | 0.667 |
| 5.53 | 0.671 |
| 6.08 | 0.685 |
| 6.86 | 0.719 |
| 8.14 | 0.777 |
| 8.77 | 0.803 |
| 9.56 | 0.830 |
| 11.6 | 0.879 |
| 13.3 | 0.904 |
| 14.1 | 0.918 |
| 14.3 | 0.911 |
| 14.6 | 0.877 |
| 15.0 | 0.817 |

---

### SPECIFICATION TABLE NO. 79: NORMAL SPECTRAL REFLECTANCE OF CHROMIUM OXIDES

| Curve No. | Ref. No. | Year | Temperature K | Wavelength Range, µm | Geometry θ θ' | Reported Error, % | Composition (weight percent), Specifications, and Remarks |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | 28 | 1963 | 298 | 0.230-2.65 | ~0° 2π | | Cr₂O₃; sintered at 2173 K for 2 hrs (setter material Cr₂O₃); density 3.15 g cm⁻³, theoretical density 5.21 g cm⁻³; MgO reference standard; data extracted from smooth curve; [Authors' designation: Sample No. 115]. |
| 2 | 362 | 1964 | ~298 | 0.230-2.65 | 0° 2π | | Cr₂O₃; 99.5 pure powder, McGean Chemical Corp; mesh size 325; compacted at 11500 psi with highly polished stainless steel ram; data extracted from smooth curve; MgO reference standard. |
| 3* | 362 | 1964 | ~298 | 0.230-2.65 | ~0° 2π | | Similar to above specimen and conditions except compacted at 23200 psi. |
| 4 | 362 | 1964 | ~298 | 0.230-2.65 | ~0° 2π | | Similar to above specimen and conditions except compacted at 34600 psi. |
| 5 | 362 | 1964 | ~298 | 0.230-2.65 | 0° 2π | | CrO₂; 99.6 pure powder, Fisher Scientific Co.; mesh size 325; compacted at 11500 psi with highly polished stainless steel ram; data extracted from smooth curve; MgO reference standard. |
| 6* | 362 | 1964 | ~298 | 0.230-2.65 | ~0° 2π | | Similar to above specimen and conditions except compacted at 23200 psi. |
| 7 | 362 | 1964 | ~298 | 0.230-2.65 | ~0° 2π | | Similar to above specimen and conditions except compacted at 34600 psi. |

---

### DATA TABLE NO. 79: NORMAL SPECTRAL REFLECTANCE OF CHROMIUM OXIDES
[Wavelength, λ, µm; Reflectance, p; Temperature, T, K]

**CURVE 1 (T=298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.090 |
| 0.235 | 0.080 |
| 0.259 | 0.080 |
| 0.269 | 0.082 |
| 0.274 | 0.084 |
| 0.278 | 0.088 |
| 0.290 | 0.088 |
| 0.322 | 0.085 |
| 0.326 | 0.080 |
| 0.340 | 0.080 |
| 0.350 | 0.080 |
| 0.370 | 0.079 |
| 0.421 | 0.067 |
| 0.529 | 0.067 |
| 0.649 | 0.064 |
| 0.733 | 0.071 |
| 0.850 | 0.070 |
| 1.05 | 0.065 |
| 1.15 | 0.065 |
| 1.65 | 0.065 |
| 1.97 | 0.068 |
| 2.35 | 0.072 |
| 2.55 | 0.077 |
| 2.65 | 0.075 |

**CURVE 2 (T~298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.081 |
| 0.237 | 0.061 |
| 0.255 | 0.055 |
| 0.280 | 0.058 |
| 0.296 | 0.060 |
| 0.320 | 0.061 |
| 0.374 | 0.081 |
| 0.466 | 0.082 |
| 0.531 | 0.227 |
| 0.579 | 0.112 |
| 0.602 | 0.108 |
| 0.631 | 0.119 |
| 0.710 | 0.211 |
| 0.748 | 0.300 |
| 0.789 | 0.479 |
| 0.810 | 0.495 |
| 0.828 | 0.496 |
| 0.950 | 0.483 |
| 1.15 | 0.461 |
| 1.35 | 0.458 |
| 1.52 | 0.455 |
| 1.70 | 0.460 |
| 1.99 | 0.467 |
| 2.37 | 0.473 |
| 2.55 | 0.479 |
| 2.65 | 0.489 |

**CURVE 3 (T~298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.081 |
| 0.238 | 0.061 |
| 0.256 | 0.056 |
| 0.280 | 0.059 |
| 0.295 | 0.055 |
| 0.350 | 0.053 |
| 0.381 | 0.072 |
| 0.412 | 0.186 |
| 0.464 | 0.091 |
| 0.481 | 0.100 |
| 0.529 | 0.242 |
| 0.598 | 0.122 |
| 0.719 | 0.250 |
| 0.805 | 0.477 |
| 0.821 | 0.488 |
| 0.844 | 0.489 |
| 1.08 | 0.461 |
| 1.25 | 0.448 |
| 1.65 | 0.440 |
| 1.85 | 0.447 |
| 2.27 | 0.459 |
| 2.51 | 0.461 |
| 2.65 | 0.473 |

**CURVE 4 (T~298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.070 |
| 0.237 | 0.051 |
| 0.244 | 0.042 |
| 0.250 | 0.040 |
| 0.269 | 0.042 |
| 0.280 | 0.045 |
| 0.313 | 0.045 |
| 0.330 | 0.043 |
| 0.350 | 0.044 |
| 0.377 | 0.067 |
| 0.405 | 0.179 |
| 0.440 | 0.097 |
| 0.484 | 0.145 |
| 0.525 | 0.252 |
| 0.593 | 0.126 |
| 0.674 | 0.201 |
| 0.726 | 0.300 |
| 0.808 | 0.469 |
| 0.847 | 0.473 |
| 1.05 | 0.451 |
| 1.25 | 0.434 |
| 1.45 | 0.428 |
| 1.70 | 0.432 |
| 2.05 | 0.444 |
| 2.45 | 0.452 |
| 2.65 | 0.464 |

**CURVE 5 (T~298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.094 |
| 0.248 | 0.071 |
| 0.265 | 0.072 |
| 0.280 | 0.084 |
| 0.291 | 0.101 |
| 0.326 | 0.093 |
| 0.344 | 0.093 |
| 0.350 | 0.089 |
| 0.383 | 0.082 |
| 0.440 | 0.117 |
| 0.560 | 0.094 |
| 0.650 | 0.124 |
| 0.739 | 0.173 |
| 0.859 | 0.400 |
| 0.966 | 0.668 |
| 1.02 | 0.757 |
| 1.08 | 0.798 |
| 1.16 | 0.814 |
| 1.22 | 0.826 |
| 1.29 | 0.826 |
| 1.34 | 0.815 |
| 1.42 | 0.735 |
| 1.54 | 0.769 |
| 1.64 | 0.763 |
| 1.82 | 0.717 |
| 1.87 | 0.673 |
| 1.93 | 0.511 |
| 1.95 | 0.524 |
| 2.09 | 0.637 |
| 2.13 | 0.645 |
| 2.18 | 0.638 |
| 2.27 | 0.579 |
| 2.37 | 0.488 |
| 2.57 | 0.350 |
| 2.62 | 0.337 |
| 2.65 | 0.337 |

**CURVE 6 (T~298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.092 |
| 0.256 | 0.067 |
| 0.287 | 0.989 |
| 0.299 | 0.098 |
| 0.307 | 0.093 |
| 0.346 | 0.092 |
| 0.350 | 0.082 |
| 0.368 | 0.077 |
| 0.436 | 0.117 |
| 0.570 | 0.095 |
| 0.673 | 0.134 |
| 0.772 | 0.209 |
| 0.876 | 0.426 |
| 0.985 | 0.668 |
| 1.04 | 0.762 |
| 1.19 | 0.804 |
| 1.32 | 0.810 |
| 1.38 | 0.778 |
| 1.42 | 0.707 |
| 1.44 | 0.700 |
| 1.45 | 0.709 |
| 1.48 | 0.735 |
| 1.52 | 0.747 |
| 1.59 | 0.752 |
| 1.67 | 0.746 |
| 1.80 | 0.699 |
| 1.85 | 0.678 |
| 1.92 | 0.469 |
| 1.94 | 0.460 |
| 1.96 | 0.468 |
| 2.09 | 0.596 |
| 2.14 | 0.599 |
| 2.20 | 0.595 |
| 2.26 | 0.558 |
| 2.33 | 0.493 |
| 2.44 | 0.400 |
| 2.61 | 0.290 |
| 2.65 | 0.283 |

**CURVE 7 (T~298)**

| λ | p |
| :--- | :--- |
| 0.230 | 0.090 |
| 0.254 | 0.064 |
| 0.277 | 0.071 |
| 0.294 | 0.089 |
| 0.309 | 0.093 |
| 0.347 | 0.090 |
| 0.366 | 0.077 |
| 0.415 | 0.104 |
| 0.429 | 0.108 |
| 0.452 | 0.106 |
| 0.537 | 0.090 |
| 0.692 | 0.130 |
| 0.753 | 0.180 |
| 0.922 | 0.500 |
| 0.991 | 0.599 |
| 1.07 | 0.647 |
| 1.19 | 0.661 |
| 1.32 | 0.660 |
| 1.37 | 0.638 |
| 1.39 | 0.610 |
| 1.42 | 0.588 |
| 1.51 | 0.615 |
| 1.59 | 0.621 |
| 1.74 | 0.601 |
| 1.84 | 0.573 |
| 1.88 | 0.540 |
| 1.92 | 0.410 |
| 1.94 | 0.400 |
| 2.04 | 0.489 |
| 2.11 | 0.517 |
| 2.15 | 0.520 |
| 2.20 | 0.512 |
| 2.40 | 0.399 |
| 2.51 | 0.309 |
| 2.61 | 0.270 |
| 2.65 | 0.266 |